name: msimne
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - rasterio
  - geopandas
  - rioxarray
  - xarray
  - numpy
  - pandas
  - shapely>=2.0
  - psutil
  - pyproj
  - pyogrio
  - dask
  - distributed
  - pystac-client>=0.7
  - odc-stac
  - planetary-computer
  - python-dateutil
  - requests
  - pip
  - pytest
  - tqdm
